---
- name: Template docker-compose file
  tags: docker-compose
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: ./docker-compose.yaml
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: 0644

- name: Copy initial config file for Home Assistant
  tags: homeassistant,config
  ansible.builtin.copy:
    src: configuration.yaml
    dest: /opt/homeassistant/core/config/
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: 0644

- name: Check if Docker Compose plugin is installed
  command: docker plugin ls --filter name=docker/compose
  register: compose_plugin
  ignore_errors: true

- name: Install Docker Compose plugin
  command: docker plugin install --alias compose docker/compose:latest
  when: compose_plugin.stdout == ""

- name: Check if Docker is installed
  command: docker --version
  register: docker_version
  ignore_errors: true

- name: Install Docker
  package:
    name: docker-ce
    state: present
  when: docker_version.rc != 0

- name: Copy multiple files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /path/to/destination/
  loop:
    - /path/to/local/file1
    - /path/to/local/file2
    - /path/to/local/file3

- name: Copy multiple files
  copy:
    src: "/path/to/local/*.txt"
    dest: /path/to/destination/

