---
- name: Template docker-compose file
  tags: docker-compose
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ ha.base_path }}/docker-compose.yaml"
    owner: "{{ user.id }}"
    mode: '0644'

- name: Start Home Assistant containers
  ansible.builtin.command: "docker compose -f {{ ha.base_path }}/docker-compose.yaml up -d"
  register: ha_started
  changed_when: ha_started.rc == 0

- name: Wait for directory to be created in container
  ansible.builtin.wait_for:
    path: "{{ ha.config_path }}/.storage"
    state: present

- name: Template Home Assistant secrets
  ansible.builtin.template:
    src: secrets.yaml.j2
    dest: "{{ ha.config_path }}/secrets.yaml"
    owner: "{{ user.id }}"
    mode: '0644'

- name: Copy initial Home Assistant config file
  ansible.builtin.copy:
    src: configuration.yaml
    dest: "{{ ha.config_path }}"
    owner: "{{ user.id }}"
    mode: '0644'

- name: Try install HACS addon
  block:
    - name: Install HACS addon
      ansible.builtin.shell:
        cmd: wget -O - https://get.hacs.xyz | bash -
        chdir: "{{ ha.config_path }}"
        creates: "{{ ha.config_path }}/custom_components/hacs"
      notify:
        - Restart Home Assistant
  rescue:
    - name: Rollback
      ansible.builtin.file:
        path: "{{ ha.config_path }}/custom_components/hacs"
        state: absent
