- name: Install Docker and Docker Compose
  tags: docker-compose
  ansible.builtin.import_tasks: docker.yml

- name: Copy docker-compose file
  tags: docker-compose, homeassistant
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "{{ ha.base_path }}/docker-compose.yaml"
    owner: "{{ user.id }}"
    mode: '0644'

- name: Start Home Assistant containers
  tags: docker-compose
  ansible.builtin.command: "docker compose -f {{ ha.base_path }}/docker-compose.yaml up -d"
  register: ha_started
  changed_when: ha_started.rc == 0

- name: Wait for directory to be created in container
  tags: docker-compose, homeassistant
  ansible.builtin.wait_for:
    path: "{{ ha.config_path }}/.storage"
    state: present

- name: Template Home Assistant secrets
  tags: homeassistant
  ansible.builtin.template:
    src: secrets.yaml.j2
    dest: "{{ ha.config_path }}/secrets.yaml"
    owner: "{{ user.id }}"
    mode: '0644'

- name: Copy initial Home Assistant config file
  tags: homeassistant
  ansible.builtin.copy:
    src: configuration.yaml
    dest: "{{ ha.config_path }}"
    owner: "{{ user.id }}"
    mode: '0644'

- name: Install HACS
  tags: homeassistant, hacs
  ansible.builtin.import_tasks: hacs.yml
