user:
  id: "1000"
db:
  name: "homeassistant"
  user: "ha_db_usr"
  password: "ha_db_pwd"
  root_password: "ha_db_admin"
ha:
  base_path: "/opt/homeassistant"
  config_path: "{{ ha.base_path }}/core/config"

# https://github.com/sarunas-zilinskas/docker-compose-macvlan
nic_name: "eth0"  # Host nic interface name
dockernetwork_name: "dockervlan"
docker_routing_interface_name: "dockerrouteif"
network_subnet: "192.168.0.0/24"
network_ip_range: "192.168.0.64/26"
network_gateway: "192.168.0.1"
dockernetwork_ip_address: "192.168.0.249/32"
dockernetwork_ip_range: "192.168.0.64/26"  # dockernetwork_ip_range can not be bigger than network_ip_range but can be the same size.
portainer_ip: "192.168.0.60"
