- name: Template Bind9 config file
  tags: dns, bind9
  ansible.builtin.template:
    src: bind/
    dest: "{{ dns.bind_path }}/"
    owner: "{{ user.id }}"
    mode: '0644'
  when: dns.service == "bind9"

- name: Copy Dnsmasq config file
  tags: dns, dnsmasq
  ansible.builtin.copy:
    src: dnsmasq/
    dest: "{{ dns.dnsmasq_path }}/"
    owner: "{{ user.id }}"
    mode: '0644'
  when: dns.service == "pihole"
  